openapi: 3.0.0
servers:
  - url: https://m8owayfzfd.execute-api.ap-northeast-1.amazonaws.com/dev
info:
  title: go-lambda-api
  version: 1.0.0
paths:
  /eventtest:
    get:
      security:
        - aws_iam: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/msg"
              example: 
                msg: 000000000000000
components:
  schemas:
    msg:
      type: string
      format: 半角英数字100文字
      maxLength: 100
      description: ステータスメッセージです。
      example: 
        message: 000000000000000

